package Clases;
// Generated 20-ene-2020 11:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private int idEquipo;
     private Liga liga;
     private String nombre;
     private String presidente;
     private Set jugadors = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    public Equipo(int idEquipo, Liga liga, String nombre, String presidente, Set jugadors) {
       this.idEquipo = idEquipo;
       this.liga = liga;
       this.nombre = nombre;
       this.presidente = presidente;
       this.jugadors = jugadors;
    }
   
    public int getidEquipo() {
        return this.idEquipo;
    }
    
    public void setidEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }
    public Set getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set jugadors) {
        this.jugadors = jugadors;
    }




}


