package Clases;
// Generated 20-ene-2020 11:02:30 by Hibernate Tools 4.3.1



/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private int idJugador;
     private Equipo equipo;
     private String nombre;
     private Integer edad;

    public Jugador() {
    }

	
    public Jugador(int idJugador) {
        this.idJugador = idJugador;
    }
    public Jugador(int idJugador, Equipo equipo, String nombre, Integer edad) {
       this.idJugador = idJugador;
       this.equipo = equipo;
       this.nombre = nombre;
       this.edad = edad;
    }
   
    public int getidJugador() {
        return this.idJugador;
    }
    
    public void setidJugador(int idJugador) {
        this.idJugador = idJugador;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


