package Clases;
// Generated 20-ene-2020 11:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Liga generated by hbm2java
 */
public class Liga  implements java.io.Serializable {


     private int idLiga;
     private Pais pais;
     private String nombre;
     private Integer division;
     private Set equipos = new HashSet(0);

    public Liga() {
    }

	
    public Liga(int idLiga) {
        this.idLiga = idLiga;
    }
    public Liga(int idLiga, Pais pais, String nombre, Integer division, Set equipos) {
       this.idLiga = idLiga;
       this.pais = pais;
       this.nombre = nombre;
       this.division = division;
       this.equipos = equipos;
    }
   
    public int getidLiga() {
        return this.idLiga;
    }
    
    public void setidLiga(int idLiga) {
        this.idLiga = idLiga;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getDivision() {
        return this.division;
    }
    
    public void setDivision(Integer division) {
        this.division = division;
    }
    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }




}


