package Clases;
// Generated 20-ene-2020 11:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int idPais;
     private String nombre;
     private String zonaHoraria;
     private String continente;
     private Set ligas = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int idPais) {
        this.idPais = idPais;
    }
    public Pais(int idPais, String nombre, String zonaHoraria, String continente, Set ligas) {
       this.idPais = idPais;
       this.nombre = nombre;
       this.zonaHoraria = zonaHoraria;
       this.continente = continente;
       this.ligas = ligas;
    }
   
    public int getidPais() {
        return this.idPais;
    }
    
    public void setidPais(int idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getzonaHoraria() {
        return this.zonaHoraria;
    }
    
    public void setzonaHoraria(String zonaHoraria) {
        this.zonaHoraria = zonaHoraria;
    }
    public String getContinente() {
        return this.continente;
    }
    
    public void setContinente(String continente) {
        this.continente = continente;
    }
    public Set getLigas() {
        return this.ligas;
    }
    
    public void setLigas(Set ligas) {
        this.ligas = ligas;
    }




}


